-- noinspection SqlResolveForFile
-- noinspection SqlNoDataSourceInspectionForFile

select
    dom_first_text(dom, '#productTitle') as `title`,
    dom_base_uri(dom) as `url`,
    str_substring_after(dom_first_href(dom, '#wayfinding-breadcrumbs_container ul li:last-child a'), '&node=') as `category`,
    dom_all_hrefs(dom, '#wayfinding-breadcrumbs_container ul li a') as `categorylevel`,
    dom_all_hrefs(dom, '#wayfinding-breadcrumbs_container ul li a') as `categorypath`,
    dom_all_hrefs(dom, '#wayfinding-breadcrumbs_container ul li a') as `categorypathlevel`,
    dom_first_text(dom, '#wayfinding-breadcrumbs_container ul li:last-child a') as `categoryname`,
    dom_all_texts(dom, '#wayfinding-breadcrumbs_container ul li a') as `categorynamelevel`,
    dom_first_slim_html(dom, '#bylineInfo') as `brand`,
    dom_all_slim_htmls(dom, '#imageBlock img') as `gallery`,
    dom_first_slim_html(dom, '#landingImage, #imgTagWrapperId img, #imageBlock img:expr(width > 400)') as `img`,
    dom_first_text(dom, '#price tr td:contains(List Price) ~ td') as `listprice`,
    dom_first_text(dom, '#price tr td:matches(^Price) ~ td') as `price`,
    str_is_not_empty(dom_first_text(dom, '#acBadge_feature_div i:contains(Best Seller)')) as `isbs`,
    str_is_not_empty(dom_first_text(dom, '#acBadge_feature_div span:contains(Amazon)')) as `isac`,
    str_is_not_empty(dom_first_text(dom, '#couponBadgeRegularVpc span:contains(Coupon)')) as `iscoupon`,
    dom_all_hrefs(dom, '#usedbuyBox div:contains(Sold by) a[href~=seller], #merchant-info a[href~=seller]') as `soldby`,
    dom_all_hrefs(dom, '#usedbuyBox div:contains(Sold by) a[href~=seller], #merchant-info a[href~=seller]') as `sellerID`,
    dom_all_hrefs(dom, '#usedbuyBox div:contains(Sold by) a[href~=seller], #merchant-info a[href~=seller]') as `marketplaceID`,
    dom_first_text(dom, '#desktop_buybox #merchant-info') as `shipby`,
    dom_first_text(dom, '#availability, #outOfStock') as `instock`,
    dom_all_hrefs(dom, '#availability a, #olp-upd-new-used a, #olp-upd-new a, #certified-refurbished-version a[href~=/dp/], #newer-version a[href~=/dp/]') as `sellsameurl`,
    str_substring_between(dom_first_text(dom, '#olp-upd-new-used a, #olp-upd-new a'), '(', ')') as `othersellernum`,
    str_is_not_empty(dom_first_text(dom, '#addToCart_feature_div span:contains(Add to Cart), #submit.add-to-cart-ubb-announce')) as `isaddcart`,
    str_is_not_empty(dom_first_text(dom, '#buyNow span:contains(Buy now)')) as `isbuy`,
    dom_first_text(dom, '#productDescription, h2:contains(Product Description) + div') as `desc`,
    dom_all_slim_htmls(dom, '#prodDetails h1:contains(Feedback) ~ div a') as `feedbackurl`,
    dom_first_text(dom, '#prodDetails table tr > th:contains(ASIN) ~ td') as `asin`,
    dom_attr(dom, '_ps_pasin') as `pasin`,
    dom_first_text(dom, '#prodDetails table tr > th:contains(Product Dimensions) ~ td') as `volume`,
    dom_first_text(dom, '#prodDetails table tr > th:contains(Item Weight) ~ td') as `weight`,
    dom_html(dom_parent(dom_select_nth(dom, '#prodDetails table tr > th:contains(Best Sellers Rank) ~ td a', 1))) as `bigrank`,
    dom_html(dom_parent(dom_select_nth(dom, '#prodDetails table tr > th:contains(Best Sellers Rank) ~ td a', 2))) as `smallrank`,
    dom_first_text(dom, '#prodDetails table tr > th:contains(Date First) ~ td') as `onsaletime`,
    is_not_empty(dom_all_imgs(dom, '#prodDetails img[src]')) as `isa`,
    str_first_integer(dom_first_text(dom, '#askATFLink, .askTopQandALoadMoreQuestions a'), 0) as `qanum`,
    str_first_integer(dom_first_text(dom, '#reviewsMedley span:contains(customer ratings)'), 0) as `reviews`,
    dom_all_slim_htmls(dom, '#reviewsMedley h3:contains(Read reviews that mention) ~ div a') as `reviewsmention`,
    str_first_float(dom_first_text(dom, '#reviewsMedley .AverageCustomerReviews span:contains(out of)'), 0.0) as `score`,
    str_first_integer(dom_first_text(dom, '#reviewsMedley div span:contains(customer ratings)'), 0) as `starnum`,
    dom_first_text(dom, 'table#histogramTable:expr(width > 100) td:contains(5 star) ~ td:contains(%)') as `score5percent`,
    dom_first_text(dom, 'table#histogramTable:expr(width > 100) td:contains(4 star) ~ td:contains(%)') as `score4percent`,
    dom_first_text(dom, 'table#histogramTable:expr(width > 100) td:contains(3 star) ~ td:contains(%)') as `score3percent`,
    dom_first_text(dom, 'table#histogramTable:expr(width > 100) td:contains(2 star) ~ td:contains(%)') as `score2percent`,
    dom_first_text(dom, 'table#histogramTable:expr(width > 100) td:contains(1 star) ~ td:contains(%)') as `score1percent`,
    dom_first_href(dom, '#reviews-medley-footer a') as `reviewsurl`
from dom_select(dom_load('{{url}}'), ':root body');
